### ISSUE TITLE
C172 checklist named C152

### ISSUE THREAD

**Issue by AnkoCazemier** [JoeriSmits/FA_Ideas_Issues#14]
##ERRORS

http://static.flight-academy.nl/documents/documents-preflight/training/niveau2/02-D%20Cessna172-checklist.pdf

When opening file the tab page says C152-CHECKLIST ... ..  in stead of C172-CHECKLIST

**Comment by JoeriSmits** [comment]
@Hankeman pak jij dit even op?

**Comment by Hankeman65** [comment]
This flight checklist is indeed for the C172. So maybe you can check if the text is correct at our webpage..

**Comment by Hankeman65** [comment]
I have also checked at the dashboard, the C172 is written, and also the correct PDF opened for the C172 checklist.
