### ISSUE TITLE
Chapters are hard to read

### ISSUE THREAD

**Issue by etkArduino** [JoeriSmits/FA_Ideas_Issues#23]
A lot of lessons are hard to read. 
This is because the texts are images rather than plain texts.
This is rather fatigueing.  Would be nice to have crisp and clear texts.

**Comment by JoeriSmits** [comment]
@aceo-henk Kan jij dit oppakken
Voor deze documenten: 
- https://docs.google.com/document/d/181i_t3QjLuQNVGyB9uDL822eNG5y-GM22P1MKpAjfTE/edit
- https://docs.google.com/document/d/1N9_fZvGjnOyuRuYKcb79DLl1ChVmqNoL5OFFTn_v6jg/edit

@etkArduino Als je nog meer documenten hebt kan je deze dan aanvullen als comment met de link van het document? Thanks.

**Comment by etkArduino** [comment]
Joeri,

Hier nog een paar ...

https://docs.google.com/document/d/1u-YfM8T7G1z3Fmpo9nBJ6-Q7tFGAJaRMvMaS6djecU0/edit
https://docs.google.com/document/d/1y1amqVX6a0qfHjBb5CiLapY8mkOVEtv5P-guo5Huszg/edit
https://docs.google.com/document/d/1uukZMeSpI_abiuAQqeDUZvBJSCn9Lb93EVea6kgj4NY/edit
https://docs.google.com/document/d/1f0vDmOG5-V7hsPFbPZQaQYcPyvkwFnxkY6TtWMw-LQo/edit
https://docs.google.com/document/d/1imJsbF4RVnUFBiuzKbcgttdmbcGWnR-Vab-1ugezvrE/edit
https://docs.google.com/document/d/1_hhskeVzhLKR9-QuiBU2Q_NOUpmhK8-GvwDIbYhvoOM/edit
....

Ik denk dat alles nog even nagelopen moete worden.

Groeten,

Eric kok




Op 21 februari 2017 om 20:17 schreef Joeri Smits <notifications@github.com>:

**Comment by etkArduino** [comment]
Hierbij screenshots van zomaar een hoofdstuk level3.

Het zijn duidelijk image bestanden. Als je die vergroot dan zie de pixels.
Vermoeiend om te lezen ...

Groeten,

Eric Kok

Op 1 jul. 2017 00:16 schreef "Joeri Smits" <notifications@github.com>:

**Comment by JoeriSmits** [comment]
@etkArduino Thanks, ik heb dit overlegd met Henk. Echter gaan we dit niet oplossen. De afbeeldingen komen uit FAA stof en om deze over te typen is momenteel teveel werk voor ons.

**Comment by etkArduino** [comment]
Hi Joeri,

Ik snap dat dat veel werk is!
Maar als jullie de kwaliteit van het materiaal willen verbeteren dan kan
deze aan het wensenlijstje toegevoegd worden ... 😉

In ieder geval bedankt.

Groeten,

Eric Kok
Op 10 jul. 2017 16:56 schreef "Joeri Smits" <notifications@github.com>:
