### ISSUE TITLE
agenda

### ISSUE THREAD

**Issue by aceo-henk** [JoeriSmits/FA_Ideas_Issues#3]
Is it possible the assign an agenda into the dashboard, so that the existing google-agenda is explored.?  Or perhaps a synchronized with Office agenda.   Also is there a possibility to synchronize the time students are active with there class?  So we can check how long students are busy with there course.  In column lay-out or such?  Or a clock which starts running and passed time becomes green or so.   Just a view things to think about...

**Comment by JoeriSmits** [comment]
I can make an agenda in the dashboard where you can make appointments with your students by (for example) click on a button "new appointment". These appointments are viewable for the trainer and the student. I can make a small button with export to google agenda to add the appointment to your google agenda.
Appointments can be seen on the home of the dashboard. 

Is this something you would use over the google agenda?

**Comment by aceo-henk** [comment]
the agenda is a good idea.  as today, i would use the agenda as such.  perhaps the CEO is even more convenient with this idea.  for me it's a go.

**Comment by Hankeman65** [comment]
We need to check also if microsoft office will work too. I like the software..

**Comment by JoeriSmits** [comment]
Almost finished only need to set the first upcoming training for student on the home. Also need to make an export button to Google Calendar and Outlook (If possible).
