### ISSUE TITLE
CEO has wishes so Admins has an overview onto trainers and there students. Possible?

### ISSUE THREAD

**Issue by aceo-henk** [JoeriSmits/FA_Ideas_Issues#7]

**Comment by JoeriSmits** [comment]
@Hankeman65 Hoe zie je dit voor je? Kan die bijvoorbeeld in manage users worden verwerkt? Ik wil zo min mogelijk pagina's maken. Misschien even een screenshotje met aantekening hoe je dit wil hebben. Thanks
